### ISSUE TITLE
Item-duplication possible

### ISSUE THREAD

**Issue by Meatroach** [WoodsMc09/DeathChest#3]
If a player does not use the dime and retrieves one item and then closes the chest & reopens it, the item is retrievable again.

This makes it possible to dublicate items indefinitely

**Comment by WoodsMc09** [comment]
has this happend? because I am sure that I made it so you can’t collect the items from the chest you have to use the green dye and then the “claim sign” disappears without the sign nothing can be collected. 

Thanks for the FeedBack!

**Comment by Meatroach** [comment]
hi

it just got reported by one of my player and i can replicate the issue. I can collect items without the dye

**Comment by WoodsMc09** [comment]
okay, I will fix the problem, I am sorry this didn’t happen when I was testing the plugin before it got released.

**Comment by Meatroach** [comment]
not a problem at all, im very thankful for you effort

**Comment by WoodsMc09** [comment]
The newest version of DeathChest should be fixed!
https://www.spigotmc.org/resources/deathchest.98898/

Thank You for your FeedBack!
